### ISSUE TITLE
only create one request invitation

### ISSUE THREAD

**Issue by santiaago** [taironas/gonawin#649] opened 2015-06-05 06:51 UTC

**Comment by rjourde** [comment] 2015-09-22 12:58
Do you have a test case?

I don't see how I can reproduce this because the button is disabled after requesting an invitation.

**Comment by santiaago** [comment] 2015-09-22 13:47
User can ask to join a team multiple times. I think that is how you get that issue

**Comment by rjourde** [comment] 2015-09-22 13:50
User will be able to request again an invitation after the current one has been denied.

**Comment by santiaago** [comment] 2015-09-22 13:57
can you force (try to create another request) the controller should not create a new request if one already exist and has not been handled.

**Comment by rjourde** [comment] 2015-09-22 14:01
Yes I agree. I can try to force another request.

**Comment by santiaago** [comment] 2015-09-22 14:29
:+1:

**Comment by rjourde** [comment] 2015-09-24 08:14
PR merged and deployed.

**Closed by rjourde** 2015-09-24 08:14 UTC
